layout_spectrum: 0.8279409
typography_spectrum: 0.1905279
color:
  saturation: 0.1947623
  lightness: 0.844268
  brandStrength: 0.05573995
  rhythmicContrast: 0.2854316
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Vreel
